<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>44ffc507-6cec-4974-aecb-ec6570b8d44b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'Input 2' to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
