<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check certification</name>
  <uuid>cec0599e-1ac7-4921-ba2f-fde8db6f99a9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
if
    there is one Certification in the certificationses of Company
        where the code of this Certification is "HEATPUMP_INSTALLER"
        and the startDate of this Certification is before or the same as 'Install date'
        and the endDate of this Certification is after 'Install date' , then set decision to true ; 
else set decision to false ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
