<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Assess company</name>
  <uuid>bb15a84f-23b8-4730-844a-2b82aed862d4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
definitions
    set 'company valid' to the assess company computed from
        Company being Company ,
        Install date being 'Install date' ;

    if
    'company valid'
then
    set the decision of decision to ACCEPTED ;
else
    set the decision of decision to REJECTED ;
    add "The company used to install the heatpump is not valid" to the messageses of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
