<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Definitions</name>
  <uuid>c28f40a2-8a0b-405b-a297-b12aac1693e1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assessment where
        the decision is MANUAL ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
