<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c933f83d-d632-4944-a22d-9f04ad4ff2c3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assessment where
        the decision is MANUAL, 
        the messageses are { "Could not assess company" } ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
