<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>0524c9c2-829e-4bac-90c9-a49d11541916</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'Input 3' to a new CompositeTest where
        the integerInput is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
