<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Definitions</name>
  <uuid>58d9bda9-1125-4d45-9eac-7ab3df1288d1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assessment where
        the decision is MANUAL ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
