<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Add one</name>
  <uuid>177b6738-eb7e-470d-815e-af94b26061c0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Input is more than 0    
then
    set decision to Input + 1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
