<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Assess device</name>
  <uuid>af150b99-c811-4bcb-bd0f-bfeccfc29ec8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
    set decision to the assess device computed from
        Device being Device ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
