<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Definitions</name>
  <uuid>ae53f4e0-9013-404e-9175-544b9825d627</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assessment where
        the amount is 0, 
        the decision is MANUAL ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
