<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ff1d9a1e-c13d-4e37-b60d-f18cf078b7cd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
    set decision to a new Assessment where
        the amount is 0 ,
        the decision is MANUAL ,
        the messageses are { "Could not assess device" } ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
