<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check date</name>
  <uuid>bde1e5e4-f627-4437-90f7-d72f1b481cb5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
if
    Input is before 1/1/2021 1:27:00 PM
then
    set decision to "KLOPT" ;
else
    set decision to "KLOPT NIET" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
