<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check install date</name>
  <uuid>7584ea2d-d2f3-45e1-9917-f473acbec6a6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Install date' is not null
then
    set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
