<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>246bbd24-bcb9-448a-a2f3-975783514862</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
