<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Assess dates</name>
  <uuid>f82efdd9-3bdc-43fe-a226-491ad1e897ed</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
definitions
    set 'six months before request' to ( 'Request date' - 6 months ) ;
if
    all of the following conditions are true :
        - 'Install date' is after or the same as 'six months before request'
        - 'Install date' is before 'Request date'
        - 'Purchase date' is after or the same as 1/1/2018 12:00:00 AM
        - 'Purchase date' is before or the same as 'Install date'
then
    set the decision of decision to ACCEPTED ;
else
    set the decision of decision to REJECTED ;
    add "The dates are incorrect" to the messageses of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
