<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c86b1041-bd60-47a6-8fb8-e8272029fcbd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assessment where
        the decision is MANUAL;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
