<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Assess max power</name>
  <uuid>ec733a86-d2b2-4359-becf-30036b16643f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
if
    the power of Device is more than 70
then
    set the decision of decision to REJECTED ;
    add "The device consumes too much power" to the messageses of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
