<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Definitions</name>
  <uuid>c4bb705a-bf72-43f2-bbc9-c686043e36f6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
    set decision to a new Assessment where
        the decision is MANUAL ,
        the amount is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
