<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0d1fe574-2074-4859-b17b-9368ead69896</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assessment where
        the decision is MANUAL, 
        the messageses are { "The device could not be assessed" } ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
