<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>DateFirst</name>
  <uuid>ada95fab-8a2f-437d-a8ae-a8f99ddc07ab</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
if
    the DateFirst of DateTest is before 1/1/2021 1:54:00 PM 
then
    set decision to "Tesst" ;
else
    set decision to "Test after" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
